### ISSUE TITLE
Validation du panier

### ISSUE THREAD

**Issue by LaurencePortron** [WildCodeSchool/lyon-js-sept2020-p3-vh-front-office#13]
En tant que visiteur connecté, je souhaite voir un listing des évènements que j’ai ajouté à mon “panier” et pouvoir valider mes réservations afin de signifier mon engagement pour participer aux activités
Un disclaimer précise que je m’engage à honorer la transaction financière en attente de la mise en place d’un moyen de paiement.

**Comment by nicolasdantas** [comment]
En tant que visiteur connecté, je souhaite voir un listing des évènements que j’ai ajouté à mon “panier” et pouvoir valider mes réservations afin de signifier mon engagement pour participer aux activités
